FROM nginx:alpine

# Remove the default Nginx HTML
RUN rm -rf /usr/share/nginx/html/*

# Copy your static files into the Nginx document root
COPY frontend/templates/index.html /usr/share/nginx/html/
COPY frontend/static /usr/share/nginx/html/static

# Copy the custom nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
