FROM python:3.9-slim

WORKDIR /app

# Install Python dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy all backend code
# This includes app.py, backend/, preprocessing/, etc.
COPY app.py /app/
COPY backend /app/backend
COPY preprocessing /app/preprocessing

# Expose port for backend
EXPOSE 8080

# Run gunicorn to serve the Flask app
CMD ["gunicorn", "--log-level", "debug", "-b", "0.0.0.0:8080", "app:app"]