name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  actions: write  # Required for updating repository variables
  contents: read

jobs:
  # ------------------------------------------------------------------------
  # 1) Run Unit Tests (Python + JavaScript)
  # ------------------------------------------------------------------------
  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ------------------ Python Tests ------------------ #
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install Python Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Unit Tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          source venv/bin/activate
          pytest tests/test_app.py tests/test_preprocessing.py

      # ------------------ JavaScript Tests ------------------ #
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Install Node.js Dependencies
        run: npm install

      - name: Run JavaScript Unit Tests
        run: npm test

  # ------------------------------------------------------------------------
  # 2) Snyk Scans (Python, Node.js, and Terraform IaC)
  # ------------------------------------------------------------------------
  snyk-scan:
    name: Snyk Scan
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # ------------------ Node.js Dependencies Scan ------------------ #
      - name: Install Node.js Dependencies for Snyk
        run: npm install

      - name: Run Snyk Node.js Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # ------------------ Terraform IaC Scan ------------------ #
      - name: Run Snyk Terraform IaC Scan
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
        continue-on-error: false

  # ------------------------------------------------------------------------
  # 3) Deploy Infrastructure (ECR and ACM)
  # ------------------------------------------------------------------------
  deploy-infrastructure:
    name: Deploy ECR & ACM
    needs: snyk-scan
    runs-on: ubuntu-latest

    # Dynamically set ENV_SUFFIX based on branch
    env:
      ENV_SUFFIX: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

    outputs:
      ecr_repo_url: ${{ steps.get_ecr_url.outputs.ecr_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: infrastructure/environment/${{ env.ENV_SUFFIX }}
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: terraform init

      - name: Terraform Plan (ECR and ACM)
        working-directory: infrastructure/environment/${{ env.ENV_SUFFIX }}
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        run: terraform plan -target=module.ecr.aws_ecr_repository.ecr -target=module.acm.aws_acm_certificate.chatbot_cert

      - name: Terraform Apply (ECR and ACM)
        working-directory: infrastructure/environment/${{ env.ENV_SUFFIX }}
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        run: terraform apply -auto-approve -target=module.ecr.aws_ecr_repository.ecr -target=module.acm.aws_acm_certificate.chatbot_cert

      # Capture the ECR URL from Terraform and set it as a job output
      - name: Retrieve ECR Repo URL
        id: get_ecr_url
        working-directory: infrastructure/environment/${{ env.ENV_SUFFIX }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PA_TOKEN }}
        run: |
          ecr_repo_url=$(terraform output -raw ecr_repository_url || echo "")
          if [ -z "$ecr_repo_url" ]; then
            echo "::error::ECR Repository URL is empty or null"
            exit 1
          fi
          echo "ECR Repo URL from Terraform: $ecr_repo_url"

          # 1) Make it a step output to be used in job outputs
          echo "ecr_url=$ecr_repo_url" >> $GITHUB_OUTPUT

          # 2) (Optional) Update GH repository variable for future runs
          gh variable set ECR_REPO_URL --body "$ecr_repo_url"

          echo "::add-mask::$ecr_repo_url"
          echo "Successfully saved ECR_REPO_URL to repository variables."

      - name: Debug ECR Repo URL (from job output)
        run: |
          echo "DEBUG: We haven't changed the 'vars.ECR_REPO_URL' context mid-run."
          echo "But the step output is now captured. We'll pass it to the next job."

  # ------------------------------------------------------------------------
  # 4) Build & Push Docker Images
  # ------------------------------------------------------------------------
  build-and-push:
    name: Build & Push Docker Images
    needs: deploy-infrastructure
    runs-on: ubuntu-latest

    env:
      ENV_SUFFIX: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Create unique Docker tag
        id: docker_tag
        run: echo "TAG=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Docker Login to ECR
        run: |
          ecr_repo_url="${{ needs.deploy-infrastructure.outputs.ecr_repo_url }}"
          if [ -z "$ecr_repo_url" ]; then
            echo "::error::No ECR Repo URL from previous job"
            exit 1
          fi
          aws ecr get-login-password --region eu-west-2 \
            | docker login --username AWS --password-stdin "$ecr_repo_url"

      - name: Build Backend Image
        run: |
          ecr_repo_url="${{ needs.deploy-infrastructure.outputs.ecr_repo_url }}"
          docker build \
            -t ${{ env.ENV_SUFFIX }}-chatbot:backend-${{ env.TAG }} \
            -f Dockerfile.backend .
          
          # Tag with "latest" so ECS references keep working
          docker tag \
            ${{ env.ENV_SUFFIX }}-chatbot:backend-${{ env.TAG }} \
            "$ecr_repo_url:backend-latest"
          
          # Also tag with the commit SHA
          docker tag \
            ${{ env.ENV_SUFFIX }}-chatbot:backend-${{ env.TAG }} \
            "$ecr_repo_url:backend-${{ env.TAG }}"

      - name: Push Backend Image
        run: |
          ecr_repo_url="${{ needs.deploy-infrastructure.outputs.ecr_repo_url }}"
          docker push "$ecr_repo_url:backend-latest"
          docker push "$ecr_repo_url:backend-${{ env.TAG }}"

      - name: Build Frontend Image
        run: |
          ecr_repo_url="${{ needs.deploy-infrastructure.outputs.ecr_repo_url }}"
          docker build \
            -t ${{ env.ENV_SUFFIX }}-chatbot:frontend-${{ env.TAG }} \
            -f Dockerfile.frontend .
          
          docker tag \
            ${{ env.ENV_SUFFIX }}-chatbot:frontend-${{ env.TAG }} \
            "$ecr_repo_url:frontend-latest"
          
          docker tag \
            ${{ env.ENV_SUFFIX }}-chatbot:frontend-${{ env.TAG }} \
            "$ecr_repo_url:frontend-${{ env.TAG }}"

      - name: Push Frontend Image
        run: |
          ecr_repo_url="${{ needs.deploy-infrastructure.outputs.ecr_repo_url }}"
          docker push "$ecr_repo_url:frontend-latest"
          docker push "$ecr_repo_url:frontend-${{ env.TAG }}"

  # ------------------------------------------------------------------------
  # 5) Deploy Remaining Infrastructure
  # ------------------------------------------------------------------------
  deploy-remaining:
    name: Deploy Remaining Infrastructure
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      ENV_SUFFIX: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2

      - name: Terraform Init
        working-directory: infrastructure/environment/${{ env.ENV_SUFFIX }}
        run: terraform init

      - name: Terraform Apply
        working-directory: infrastructure/environment/${{ env.ENV_SUFFIX }}
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        run: terraform apply -auto-approve
