name: Deploy

on:
  workflow_dispatch: # Allows manual triggering of the workflow from GitHub UI
  push:
    branches: [ main ] # Automatically run the workflow when code is pushed to the main branch


permissions:
  actions: write
  contents: read

jobs:
  # ------------------------------------------------------------------------
  # 1) Run Unit Tests (Python + JavaScript)
  # ------------------------------------------------------------------------
  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest # Specifies that the job should run on the latest Ubuntu environment
    steps:
      - name: Checkout Code # Clones the repository so that subsequent steps can access the code
        uses: actions/checkout@v3

      # ------------------ Python Tests ------------------ #
      - name: Set Up Python # Sets up the Python environment with the specified version
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12 # Python version to be used

      - name: Install Python Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Unit Tests
        env: # Environment variables required for running tests
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          source venv/bin/activate
          pytest tests/test_app.py tests/test_preprocessing.py

      # ------------------ JavaScript Tests ------------------ #
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Install Node.js Dependencies
        run: npm install

      - name: Run JavaScript Unit Tests
        run: npm test

  # ------------------------------------------------------------------------
  # 2) Snyk Scans (Python, Node.js, and Terraform IaC)
  # ------------------------------------------------------------------------
  snyk-scan:
    name: Snyk Scan
    needs: run-tests # This job will only run if the 'run-tests' job succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ------------------ Node.js Dependencies Scan ------------------ #
      - name: Install Node.js Dependencies for Snyk
        run: npm install

      - name: Run Snyk Node.js Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # ------------------ Terraform IaC Scan ------------------ #
      - name: Run Snyk Terraform IaC Scan
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # Snyk authentication token stored in GitHub Secrets
        with:
          args: --severity-threshold=high
        continue-on-error: false  # Set to true to ignore high severity issues

  # ------------------------------------------------------------------------
  # 3) Deploy Infrastructure (ECR and ACM)
  # ------------------------------------------------------------------------
  deploy-infrastructure:
    name: Deploy ECR & ACM
    needs: snyk-scan
    runs-on: ubuntu-latest
    env:
      # Dynamically set ENV_SUFFIX based on branch
      ENV_SUFFIX: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials # Set up AWS credentials for Terraform and AWS CLI commands
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Set up Terraform # Installs and configures Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2 # Terraform version to be used
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: infrastructure/environment/${{ env.ENV_SUFFIX }}
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: terraform init

      - name: Terraform Plan (ECR and ACM)
        working-directory: infrastructure/environment/${{ env.ENV_SUFFIX }}
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        run: terraform plan -target=module.ecr.aws_ecr_repository.ecr -target=module.acm.aws_acm_certificate.chatbot_cert

      - name: Terraform Apply (ECR and ACM)
        working-directory: infrastructure/environment/${{ env.ENV_SUFFIX }}
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        run: terraform apply -auto-approve -target=module.ecr.aws_ecr_repository.ecr -target=module.acm.aws_acm_certificate.chatbot_cert

  # ------------------------------------------------------------------------
  # 4) Build & Push Docker Images
  # ------------------------------------------------------------------------
  build-and-push:
    name: Build & Push Docker Images
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    env:
      # Hard-code the ECR URL based on branch
      ENV_SUFFIX: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
      ECR_REPO_URL: ${{ github.ref_name == 'main' && '346596735478.dkr.ecr.eu-west-2.amazonaws.com/chatbot-prod' || '346596735478.dkr.ecr.eu-west-2.amazonaws.com/chatbot-dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Create unique Docker tag # Generate a unique Docker tag based on the commit SHA
        id: docker_tag
        run: echo "TAG=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Docker Login to ECR
        run: |
          aws ecr get-login-password --region eu-west-2 \
            | docker login --username AWS --password-stdin $ECR_REPO_URL

      - name: Build Backend Image
        run: |
          echo "DEBUG: Building with tag=$TAG and ECR=$ECR_REPO_URL"
          docker build \
            -t ${{ env.ENV_SUFFIX }}-chatbot:backend-${{ env.TAG }} \
            -f Dockerfile.backend .

          # Tag with "latest" so ECS references keep working
          docker tag \
            ${{ env.ENV_SUFFIX }}-chatbot:backend-${{ env.TAG }} \
            ${{ env.ECR_REPO_URL}}:backend-latest 

          # Also tag with the commit SHA
          docker tag \
            ${{ env.ENV_SUFFIX }}-chatbot:backend-${{ env.TAG }} \
            ${{ env.ECR_REPO_URL}}:backend-${{ env.TAG }}

      - name: Push Backend Image
        run: |
          docker push ${{ env.ECR_REPO_URL}}:backend-latest
          docker push ${{ env.ECR_REPO_URL}}:backend-${{ env.TAG }}

      - name: Build Frontend Image
        run: |
          docker build \
            -t ${{ env.ENV_SUFFIX }}-chatbot:frontend-${{ env.TAG }} \
            -f Dockerfile.frontend .

          docker tag \
            ${{ env.ENV_SUFFIX }}-chatbot:frontend-${{ env.TAG }} \
            ${{ env.ECR_REPO_URL}}:frontend-latest

          docker tag \
            ${{ env.ENV_SUFFIX }}-chatbot:frontend-${{ env.TAG }} \
            ${{ env.ECR_REPO_URL}}:frontend-${{ env.TAG }}

      - name: Push Frontend Image
        run: |
          docker push ${{ env.ECR_REPO_URL}}:frontend-latest
          docker push ${{ env.ECR_REPO_URL}}:frontend-${{ env.TAG }}

  # ------------------------------------------------------------------------
  # 5) Deploy Remaining Infrastructure
  # ------------------------------------------------------------------------
  deploy-remaining:
    name: Deploy Remaining Infrastructure
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      ENV_SUFFIX: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2

      - name: Terraform Init
        working-directory: infrastructure/environment/${{ env.ENV_SUFFIX }}
        run: terraform init

      - name: Terraform Apply
        working-directory: infrastructure/environment/${{ env.ENV_SUFFIX }}
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        run: terraform apply -auto-approve
